### ISSUE TITLE
Can I use it with [toolbox]?

### ISSUE THREAD

**Issue by tokisot** [Owyn/GLS-Guide#3]
have a problem:
Error: Command already registered: gls
    at CommandBase.add (C:\Users\user\AppData\Local\Programs\TeraToolbox\mods\command\index.js:231:19)
    at Command.add (C:\Users\user\AppData\Local\Programs\TeraToolbox\mods\command\index.js:381:19)
    at new GrottoOfLostSoulsGuide (C:\Users\user\AppData\Local\Programs\TeraToolbox\mods\GLS-Guide-master\index.js:74:14)
    at ModuleManager.load (C:\Users\user\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:157:35)
    at C:\Users\user\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:122:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (C:\Users\user\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:120:31)
    at Socket.<anonymous> (C:\Users\user\AppData\Local\Programs\TeraToolbox\bin\connectionManager.js:55:47)
    at Socket.emit (events.js:215:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1114:10)

**Comment by Owyn** [comment]
`Error: Command already registered: gls`
means you already have it

**Comment by tokisot** [comment]
apparently the problem was that I tried different versions of this mod, but they did not work and I forgot to delete one of them. problem resolved
